import os

POSTGRES_TAG = os.getenv("POSTGRES_TAG")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_PORT = int(os.getenv("POSTGRES_PORT"))
AIRFLOW_CONN_POSTGRES_DEFAULT = os.getenv("AIRFLOW_CONN_POSTGRES_DEFAULT")
POSTGRES_CONN_ID = os.getenv("POSTGRES_CONN_ID", "postgres_default")
