import os

MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT")
MINIO_API_PORT = int(os.getenv("MINIO_API_PORT"))
MINIO_CONSOLE_PORT = int(os.getenv("MINIO_CONSOLE_PORT"))
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")
MINIO_ROOT_USER = os.getenv("MINIO_ROOT_USER")
MINIO_ROOT_PASSWORD = os.getenv("MINIO_ROOT_PASSWORD")
MINIO_REGION = os.getenv("MINIO_REGION")

AWS_CONN_ID = os.getenv("AWS_CONN_ID")
MINIO_CONN_TYPE = os.getenv("MINIO_CONN_TYPE")
AWS_REGION = os.getenv("AWS_REGION")
AWS_ENDPOINT_URL = os.getenv("AWS_ENDPOINT_URL")

